apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: ingress-nginx
    releaseName: ingress-nginx
    version: 4.10.0
    repo: https://kubernetes.github.io/ingress-nginx
    namespace: ingress-nginx
    valuesFile: helm-values.yaml

namespace: ingress-nginx
